name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'

      - name: Validate
        run: mvn -B verify

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build
    runs-on: ubuntu-latest
    needs: pipeline
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd lesebot
            git pull
            ./deploy.sh
